_BASE_: FastInst_Res2_table_tennis_Base.yaml
MODEL:
  WEIGHTS: "res2net101_26w_4s-02a759a1.pth"
  # WEIGHTS: "output/fastinst_r101_table_tennis_0121/model_final.pth"
  RESNETS:
    DEPTH: 101
    SCALE: 4
    WIDTH_PER_GROUP: 26
  FASTINST:
    DEC_LAYERS: 5
OUTPUT_DIR: "output/fastinst_res2_table_tennis_0126_2"
